name: cs5346-otot-a3
channels:
  - defaults
dependencies:
  - matplotlib=3.6.2
  - matplotlib-inline=0.1.6
  - pandas=1.5.2
  - plotly=5.9.0
  - python=3.10.9
  - ipywidgets==7.7.1
  - jupyterlab-widgets==1.1.1